"""Public entrypoint facades.

The eight short "start-here"-style entrypoints are thin aliases over the real
orchestrators and hubs, NOT registry skills. Their content is stored verbatim so a
generated runtime reproduces them byte-for-byte, while the routing graph and skill
catalog stay defined solely by the registry (ALL_V3_SKILLS).
"""
from __future__ import annotations


PUBLIC_ENTRYPOINT_FACADE_CONTENT: dict[str, str] = {
    'start-here': '---\nname: start-here\ndescription: Use when a request arrives and you want Relay-kit to pick the right path, next skill, and next artifact without guessing. Easiest public Relay-kit entrypoint.\n---\n\n# Start Here\n\nPublic alias for `workflow-router`.\n\nUse this when:\n- you are not sure which Relay-kit skill should go first\n- the task might be planning, building, debugging, or review\n- you want one explicit next move instead of a long internal taxonomy\n\nWhat this alias should do:\n1. decide which path the request belongs to\n2. choose the next real skill\n3. name the artifact or evidence expected next\n\nBehind the scenes:\n- canonical skill: `workflow-router`\n- common outputs: `.relay-kit/state/workflow-state.md` and the next kickoff artifact\n\nTypical handoff:\n- `brainstorm`\n- `write-steps`\n- `build-it`\n- `debug-systematically`\n- `ready-check`\n\n',
    'brainstorm': '---\nname: brainstorm\ndescription: Use when a rough idea needs to become a clear direction before implementation begins. Public Relay-kit entrypoint for brainstorming.\n---\n\n# Brainstorm\n\nPublic alias for `brainstorm-hub`.\n\nUse this when:\n- the idea is still rough\n- the user is unsure about scope or approach\n- you need to clarify purpose, constraints, and success before writing steps or code\n\nWhat this alias should do:\n1. narrow the request until it is coherent\n2. surface obvious assumptions and trade-offs\n3. decide whether the next artifact is a brief, PRD, or architecture handoff\n\nBehind the scenes:\n- canonical skill: `brainstorm-hub`\n- common outputs: `product-brief.md`, then a handoff to planning\n\nTypical handoff:\n- `start-here`\n- `write-steps`\n',
    'write-steps': '---\nname: write-steps\ndescription: Use when approved work needs to be sliced into small, buildable, verifiable implementation steps. Public Relay-kit entrypoint for implementation slicing.\n---\n\n# Write Steps\n\nPublic alias for `scrum-master`.\n\nUse this when:\n- the direction is already approved\n- the plan is still too vague for safe implementation\n- you need clear stories or a quick tech spec before building\n\nWhat this alias should do:\n1. turn the approved work into thin, verifiable slices\n2. make expected files, tests, and verification explicit\n3. hand implementation off without reopening product debates\n\nBehind the scenes:\n- canonical skill: `scrum-master`\n- common outputs: `.relay-kit/contracts/tech-spec.md` or `.relay-kit/contracts/stories/story-xxx.md`\n\nTypical handoff:\n- `build-it`\n- `ready-check`\n\n',
    'build-it': '---\nname: build-it\ndescription: Use when an approved story or tech spec is ready for implementation with controlled scope and evidence. Public Relay-kit entrypoint for building.\n---\n\n# Build It\n\nPublic alias for `developer`.\n\nUse this when:\n- planning is done\n- files need to change now\n- the next move is implementation, not more debate\n\nWhat this alias should do:\n1. implement the scoped change\n2. start from a failing test or failing reproduction when the behavior is testable\n3. keep evidence tied to the actual acceptance criteria\n4. keep code, comments, test names, placeholder copy, and sample data plain ASCII; do not add decorative icons, emojis, or odd Unicode unless the product explicitly needs them\n5. hand off with test and browser proof instead of completion claims\n\nBehind the scenes:\n- canonical skill: `developer`\n- common outputs: working code, verification evidence, updated workflow state\n\nTypical handoff:\n- `ready-check`\n- `prove-it`\n',
    'debug-systematically': '---\nname: debug-systematically\ndescription: Use when a bug, regression, flaky behavior, or mismatch needs disciplined debugging instead of guessing. Public Relay-kit entrypoint for the debug path.\n---\n\n# Debug Systematically\n\nPublic alias for `debug-hub`, with `root-cause-debugging` as the discipline path underneath it.\n\nUse this when:\n- something broke\n- a test fails but the cause is unclear\n- behavior is flaky or contradictory\n- you do not trust a quick patch\n\nWhat this alias should do:\n1. reproduce or explain why reproduction is still weak\n2. collect evidence before proposing a fix\n3. push toward root cause instead of guess-and-patch\n\nBehind the scenes:\n- canonical hub: `debug-hub`\n- discipline utility: `root-cause-debugging`\n- common output: `.relay-kit/contracts/investigation-notes.md`\n\nTypical handoff:\n- `build-it`\n- `ready-check`\n\n',
    'prove-it': '---\nname: prove-it\ndescription: Use when a completion claim needs one last evidence pass before work is called done, fixed, or ready. Public Relay-kit entrypoint for final proof.\n---\n\n# Prove It\n\nPublic alias for `evidence-before-completion`.\n\nUse this when:\n- someone is about to say the work is done\n- the claim sounds stronger than the proof\n- you want one final claim-to-evidence check\n- you need to map each claim to fresh proof output\n\nWhat this alias should do:\n1. list the exact claims being made\n2. tie each claim to fresh proof output\n3. send weak claims back for more testing or debugging\n\nBehind the scenes:\n- canonical skill: `evidence-before-completion`\n- this is not a readiness verdict\n- this alias does not write `qa-report.md`\n- common outputs: evidence added to `workflow-state.md` or the active artifact\n\nTypical handoff:\n- `ready-check`\n- `debug-systematically`\n',
    'ready-check': '---\nname: ready-check\ndescription: Use when code exists and you need a real go or no-go decision about readiness or shipability. Public Relay-kit entrypoint for review and QA gating.\n---\n\n# Ready Check\n\nPublic alias for `review-hub`, with `qa-governor` as the quality gate underneath it.\n\nUse this when:\n- code exists and you want a real go/no-go decision\n- the work looks close but confidence is uneven\n- the page works technically but might still be weak in the browser\n- you already reviewed the branch or PR and now need a formal readiness verdict\n\nWhat this alias should do:\n1. compare the request, plan, implementation, and evidence\n2. reject weak completion claims\n3. decide whether to accept, rework, debug, or re-plan\n\nBehind the scenes:\n- canonical hub: `review-hub`\n- quality gate: `qa-governor`\n- common output: `.relay-kit/contracts/qa-report.md` plus a clear verdict\n\nHow this differs from `review-pr`:\n- `review-pr` is for reviewing a branch or PR and deciding what must bounce back before merge\n- `ready-check` is for a go / no-go readiness or shipability verdict\n- this is not a claim-to-evidence pass\n- `prove-it` is for one last claim-to-evidence pass when the verdict still sounds too optimistic\n\nTypical handoff:\n- `build-it`\n- `debug-systematically`\n- `review-pr`\n- `prove-it`\n\n',
    'review-pr': '---\nname: review-pr\ndescription: Use when a branch or PR needs a deliberate review before merge or sign-off. Public Relay-kit entrypoint for branch and PR review.\n---\n\n# Review PR\n\nPublic alias for `review-hub`.\n\nUse this when:\n- a branch or PR needs a deliberate review before merge\n- you want to review code that already exists and decide what should bounce back\n- you need alignment across the request, implementation, and current evidence before sign-off\n\nWhat this alias should do:\n1. review the request, implementation, and proof together\n2. call out mismatches, risks, and missing evidence\n3. decide whether the work should bounce back to planning, debugging, implementation, or readiness checking\n\nBehind the scenes:\n- canonical hub: `review-hub`\n- common outputs: a clear review verdict, concrete findings, and the next owning lane\n\nHow this differs from `ready-check`:\n- `review-pr` is for reviewing a branch or PR and deciding what must bounce back before merge\n- `ready-check` is for a formal go / no-go readiness verdict\n- `prove-it` is for one last claim-to-evidence pass when the claim still feels too optimistic\n\nTypical handoff:\n- `build-it`\n- `debug-systematically`\n- `ready-check`\n',
}


def render_public_entrypoint_facade(name: str) -> str:
    """Return the exact SKILL.md content for a public entrypoint facade."""
    return PUBLIC_ENTRYPOINT_FACADE_CONTENT[name]

